### PR TITLE
Update to Cesium 1.37

### LINKED ISSUE #72: Update Bing key
Rather than using the key that ships with Cesium, we should use the cesiumjs.org Bing key (or a non-bing imagery provider)

### LINKED ISSUE #78: Fix examples and clean up README.md
@hpinkos do you have any bandwidth to make these updates soon?

Perhaps just upgrade to Cesium 1.37, test, and clean up the HTML that no longer renders in the README.md?

Later, we can get a separate Bing key, #72.

We want to show these in an upcoming event.

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #78
Fixes #72

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks for the quick fix, @hpinkos!

@ggetz could you please test?

**Comment by ggetz** [comment]
In the pinPoint demo, when you load it zooms in and clips through the surface.

**Comment by ggetz** [comment]
In the polygonStyle demo, the red outline doesn't show up.

**Comment by ggetz** [comment]
@hpinkos Other than that, these all look good.

**Comment by hpinkos** [comment]
Thanks @ggetz! Fixed

**Comment by ggetz** [comment]
Looks good! @pjcozzi this looks good to merge.

**Comment by pjcozzi** [comment]
Thanks @hpinkos @ggetz!

**Pull request merged**
