### PR TITLE
Update Cesium and fix Bing imagery

### PR DESCRIPTION
**Pull request by hpinkos**
I updated to Cesium 1.22.1 and changed the examples to use the bing key we use on Cesiumjs.org

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @hpinkos.

@JoshuaStorm would you like to verify this by pulling this branch and then briefly testing each example?

**Comment by JoshuaStorm** [comment]
Sorry I wasn't on top of my email. I'll get on this now

**Comment by JoshuaStorm** [comment]
@pjcozzi @hpinkos 
Looks good to me!

Sorry again about the delay, hopefully my new email filter will avoid that in the future.

**Comment by pjcozzi** [comment]
Thanks for the testing, @JoshuaStorm!

**Pull request merged**
