### PR TITLE
Update to Cesium 1.20

### LINKED ISSUE #73: Upgrade to Cesium 1.16
When this is released in December, it will have much better terrain/imagery performance because of fog.

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #73

### CODE REVIEW

**Comment by pjcozzi** [comment]
@tomped would you like to test this by verifying that each example still works?

**Comment by TomPed** [comment]
I found two issues.

1. Tilt Camera. I can't see the globe. http://localhost:8080/examples/cameraTilt.html
2. Smooth Animation with frameend. Not smooth; camera jumps around. http://localhost:8080/examples/frameAnimation.html

That is what I found. The others look good. 👍.

**Comment by hpinkos** [comment]
Thanks @TomPed!  I fixed those two examples

**Comment by TomPed** [comment]
I think they are all working now.

**Comment by TomPed** [comment]
I'm not that powerful yet, 😢. 
screen shot 2016-04-22 at 11 00 58 am

**Comment by pjcozzi** [comment]
Thanks @hpinkos @TomPed!

**Pull request merged**
